
export const PROFILE = {
    DEEPAK_MANDAL: "Deepak K. Mandal",
    CGI_IITG: "Sr. Software Engineer, CGI || B.Tech, IIT Guwahati",
    PRFILE_PIC: 'assets/images/Deepak_Image.jpg',
    DESCRIPTION: "~ 4 years of Professional experience in software engineering including significant expertise in Java technologies, SQL, Spring & Angular framework; with strong engineering Academic background from IIT Guwahati."
}

export const EDUCATION = {
    IIT: 'IIT / Engineering',
    IITG: 'Indian Institute of Technology, Guwahati ',
    BTECH: 'Bachelor of Technology',
    SESSION: '2017-2021',
    IITG_LOGO: 'assets/images/IITG.png',
    SENIOR_SECONDARY: 'Senior Secondary'
}

export const EXPERIENCE = {
    CGI: 'CGI / Product Engineering',
    CGI_INFO_SYS: 'CGI Information Systems and Management Consultants Pvt. Ltd.',
    SOFTWARE_CONSULTANT: 'Senior Software Engineer / CONSULTANT',
    DATACYCLE360_1: 'Worked on CGI DataCycle360 Webshop product, an eCommerce platform which is responsible for ordering items & approving purchases; Technical analysis/investigation of required functionality & features; Implemented new UI features using Angular',
    DATACYCLE360_2: 'Developed backend APIs using Spring Boot, Java, Apache Solr which involves CRUD operations, spellcheck suggest search functionality; Webshop-Advantage application integration with Purchase requests features & bug fixes.',
    DATACYCLE360_3: 'Designed database data model, schema modification using MS SQL database technologies; SQL query tuning to optimize performance.',
    
    WEALTH360_1: 'Worked as a full-stack Engineer with Product Engineering perspective on CGI Wealth360 product features in the Global Wealth and Capital Markets domain, which delivers a flexible Unified Account Platform with goal-based investing capabilities and provides end-to-end investment management support',
    WEALTH360_2: 'Technical Analysis of epic/user story, bug root cause, and designed solutions meeting industry standard.',
    WEALTH360_3: 'Angular – development of new UI screen Including the building reusable component, service with HTML, SCSS, TypeScript, AG Grid, angular material, RxJs, Lodash & JavaScript, that works in multiple areas of application; Architecture upgrades - Angular version & Ascent libraries; services-API integration; Unit testcases using Karma-Jasmine.',
    WEALTH360_4: 'Spring & PL/SQL – development of RESTful web services/API using Spring Boot, Java, Microservice architectures, Maven, Postman API and SQL/Oracle databases; testcases using Junit testing framework.',
    WEALTH360_5: 'Code fix for client/production bug in the entire codebase or product engineering environment; code reviews; ensured code quality and maintained standard coding style.',
    WEALTH360_6: 'Analysis, development, debugging, Testing, deployment & collaborating with business to ensure bug-free user experience and with PuTTY, WinSCP; DevOps:- Jenkins, Continuous Integration/Continuous Deployment, Git; Bitbucket, Confluence, Jira tools on day-to-day basis in the Agile environment',

    JAVA_FULL_STACK: 'Worked as a Java full-stack developer with Product Engineering perspective on Digital Wealth Platform (CGI Wealth360) product features in the Global Wealth and Capital Markets domain',
    UI_WORK: 'Angular – development of new UI screen, Includes building reusable component/service with HTML/SCSS/TS that works in multiple areas of application, service integration with backend API & writing Test cases using Jasmine testing framework',
    BACKEND_WORK: 'Spring & PL/SQL – development of RESTful web services/API, code fix for bugs',
    TECHNICAL_ANALYSIS: 'Technical Analysis of epic/user story, bug root cause, creating solution & its implementation',
    TECHNOLOGIES: 'Development, debugging & Testing using Spring/Java, Angular/TypeScript/JavaScript, AG-Grid/angular-material, SQL/Oracle databases; and collaborating with PuTTY, WinSCP, Jenkins, Bitbucket, Confluence, Jira, Postman API, CAST Application Intelligence Platform (AIP) tools on day-to-day basis in the Agile environment',
    ASDC: 'Asia Pacific Solutions Delivery Center, Bangalore - India',
    CGI_SESSION: '2021 - present',
    CGI_LOGO: 'assets/images/cgi.png',
    ACCENTURE: 'Accenture',
    ACCENTURE_SOL: 'Accenture Solutions Pvt. Ltd.',
    LEARNING: 'Pre-Onboard Learning',
    JAVA_ORACLE: 'Java Technologies + Oracle Database',
    ACCENTURE_SESSION: 'Aug - Sept 2021',
    ACCENTURE_LOGO: 'assets/images/ac.png',

}

export const PROJECTS = {
    REVIEWBOOK: 'ReviewBook - Java',
    REVIEWBOOK_PLATFORM: 'ReviewBook Platform',
    CGI_PRODUCT_ENGG: 'CGI - Product Engineering',
    REVIEWBOOK_PROBLEM_STATEMENT: 'Analyzed, designed & developed a product to the core problem - “How to motivate maximum number of consumers to provide genuine reviews and ratings that can influence buying decisions of other consumers”.',//'Worked on Core Problem - “How to motivate maximum number of consumers to provide genuine reviews and ratings that can influence buying decisions of other consumers”',
    REVIEWBOOK_DB_ARCH: 'Designed Architecture diagram, Database data model & schema by analyzing business requirement/high-level features.',
    REVIEWBOOK_MICROSERVICES: 'Developed microservice architecture for Registration, Login, Product management, Review management services, Eureka server, API Gateway using Spring Boot with NoSQL/MongoDB & SQL/MySQL databases. Implemented user authentication using JWT, microservices communication using RabbitMQ queuing system & containerization using Docker',//'Developed microservice architecture for Registration, Login, Product management, Review management services, Eureka server, API Gateway using Spring Boot with NoSQL/MongoDB & SQL/MySQL databases',
    REVIEWBOOK_ANGULAR_ARCH: 'Designed & built Restful APIs that involves CRUD operations. Designed angular application architecture & developed single page application corresponding to services using angular materials, AG Grid; implemented custom, shared module features.',//'Developed angular application architecture corresponding to services using angular materials, AG Grid',
    // REVIEWBOOK_TECHNOLOGIES: 'Implemented JWT authentication, microservices communication using RabbitMQ & containerization using Docker',
    REVIEWBOOK_SESSION: 'Jul. 2021- Sept. 2021',
    REVIEWBOOK_LOCATION: 'https://reviewbook.stackroute.io/',
    REVIEWBOOK_DOC_SOURCE_URL: 'https://github.com/deepak-mandal/ReviewBook',
    REVIEWBOOK_DOC_ARC_DIAGRAM: 'assets/images/product_arc_diagram.png',
    REVIEWBOOK_DOC_TECH_DIAGRAM : 'assets/images/product_tech_diagram.png',
    CONFERENCE_WEB: 'Conference Website - PHP',
    IITG_WEB: 'Conference Website',
    DOC_IITG: 'IITG',//'Dept. of Chem., IITG',
    CONFERENCE_TEAM: 'Developed PHP based full-stack web application for CRSI NSC-27 and 15th CRSI-RSC joint symposium.',//'Developed PHP based full-stack conference web app with my team members.',
    CONFERENCE_DEV: 'Developed the admin portal for the response to edit/ delete using PHP, MySQL; HTML, CSS & Bootstrap',//'Developed the admin portal for the response to edit/delete.',
    CONFERENCE_TECH: 'Technologies used: Backend - PHP, MySQL; Frontend - HTML, CSS & Bootstrap',
    CONFERENCE_SESSION: 'April 2020-June 2020',
    CONFERENCE_LOCATION: 'IIT Guwahati',
    NLP: 'Web and PDF file Data Extraction - NLP',
    NLP_TITLE: 'Web and PDF file Data Extraction',
    NLP_DUEDASH: 'DueDash',
    NLP_ACTIVITY_TEXT: 'Summarization of Text:- Generated the summary from the Source text either web link or PDF file. Further Drawn their Word Cloud',
    NLP_ACTIVITY_IMAGE: 'Text and Image Extraction from any Web Link or URL:- Extraced Images and text data from the web Links and PDF files.',
    NLP_TECH: ' Technologies used: Python3, BeautifulSoup/bs4, PyPDF2, SpaCy, NLTK, WordCloud, NumPy, Shutil, OS, parse, requests',
    NLP_LOGO: 'https://duedash.net/wp-content/uploads/2021/10/DueDash-Large2x.png',
    NLP_SESSION: 'Selected for Product Development & Testing, Internship (work remotely) at Germany based Startup',
    NLP_LOCATION: 'https://github.com/deepak-mandal/DueDash-Germany',
    CRICKET_GAME: 'Cricket Game - Python',
    INTERNSHALA_LOGO: 'assets/images/in.png',
    CRICKET_GAME_PY: 'Fantasy Cricket Game',
    INTERNSHALA: 'Internshala Trainings',
    CRICKET_GAME_ACTIVITY: 'Developed a Python-based desktop application using PyQt framework with SQLite Database.',
    CRICKET_GAME_RESULT: 'assets/images/Project-Fantasy_Cricket_Game_Evaluation.png',
    CRICKET_GAME_SESSION: 'July 2020',
    CRICKET_GAME_LOCATION: 'https://github.com/deepak-mandal/Game',
    ML: 'Price Prediction - Machine learning',
    ML_PREDICTION: 'House Price Prediction',
    ML_TECH: 'Self-paced project using Machine learning technique',
    ML_ACTIVITY: 'Built a Linear Regression Model to Predict the Sale Price of the House based on its characteristics.',
    ML_SESSION: 'April 2021-May 2021',
    ML_LOCATION: 'https://github.com/deepak-mandal/SalePricePrediction',
    AUTOMATION: 'Email Automation',
    AUTOMATION_PY: 'Email Automation with Python',
    SELF_PACED_PROJECT: 'Self-paced project',
    AUTOMATION_ACTIVITY: 'Automating emails by the help of Python, smtplib, Linux & Window OS, HTML, CSS, with attachments using Encrypted connections.',
    AUTOMATION_TECH: 'Extracted emails automatically from the Linkedin Post using selenium, chrome automated test software, re, pandas',
    AUTOMATION_FEATURE: 'Features:- Multiple emails can in one go or on single click, The delivered email is of personalised type i.e. "to" for each single email_Id but not "bcc" or "cc" e-mail type',
    AUTOMATION_SESSION: '2020',
    AUTOMATION_LOCATION: 'https://github.com/deepak-mandal/Email-Automation-with-Python',
    ANALYSIS: 'Text Analysis and Mining',
    ANALYSIS_MINING: 'Wikipedia Text Analytics and Mining',
    ANALYSIS_ACTIVITY: ' Analysed the unstructured data (article) using text mining and created the Word Cloud out of that; to understand what these article trying to say, rather than reading the entire article.',
    ANALYSIS_TECH: 'Technologies used: Python3, WordCloud',
    ANALYSIS_WORD_CLOUD: 'assets/images/tech.png',
    ANALYSIS_SESSION: 'Dec 2020',
    ANALYSIS_LOCATION: 'https://github.com/deepak-mandal/Word-Cloud-from-Text-Mining'
}

export const SKILLS = {
    PROGRAMMING_LANGUAGE: 'Programming languages',
    JAVA: 'Java',
    JAVA_LOGO: 'assets/images/java.png',
    PYTHON: 'Python',
    PY: 'assets/images/py.png',
    JAVASCRIPT: 'JavaScript',
    JS: 'assets/images/js.png',
    SQL: 'SQL',
    
    TYPESCRIPT: 'TypeScript',
    TS: 'assets/images/ts.png',
    PHP: 'php',
    PHP_LOGO: 'assets/images/php.png',
    WEB_TECHNOLOGIES: 'Web technologies',
    SPRING: 'Spring',
    SPRING_LOGO: 'assets/images/spring.png',
    ANGULAR: 'Angular',
    AG_GRID: 'AG Grid',
    AG_GRID_LOGO: 'assets/images/ag_grid.png',
    ANGULAR_MATERIALS: 'Angular materials',
    ANGULAR_MATERIALS_LOGO: 'assets/images/angular_material.png',
    ANGULAR_LOGO: 'assets/images/angular.png',
    HTML: 'HTML',
    HTML_LOGO: 'assets/images/html.png',
    CSS: 'CSS / SCSS',
    CSS_LOGO: 'assets/images/scss.png',
    BOOTSTRAP: 'BootStrap',
    BOOTSTRAP_LOGO: 'assets/images/bootstrap.jpeg',

    RXJS: 'RxJs',
    RXJS_LOGO: 'assets/images/rxjs.png',
    JUNIT: 'JUnit',
    JUNIT_LOGO: 'assets/images/JUnit.png',
    ANGULAR_TC: 'Karma-Jasmine',
    ANGULAR_TC_LOGO: 'assets/images/angular_tc.png',
    ESLINT: 'ESLint',
    ESLINT_LOGO: 'assets/images/eslint.jpg',
    SONAR: ' SonarLint',
    SONAR_LOGO: 'assets/images/sonar.svg',




    DB: 'Database management',

    ORACLE: 'Oracle',
    ORACLE_LOGO: 'assets/images/oracle.png',
    MONGODB: 'MongoDB',
    MONGODB_LOGO: 'assets/images/mongodb.png',
    MYSQL:'MySQL',
    MYSQL_LOGO: 'assets/images/mysql.png',
    MS_SQL:'MS SQL',
    MS_SQL_LOGO: 'assets/images/ms-sql.svg',
    SQLITE: 'SQLite',
    SQLITE_LOGO: 'assets/images/sqlite.png',
    ANALYTICAL_TOOLS: 'Analytical tools',
    PANDAS: 'Pandas',
    PANDAS_LOGO: 'assets/images/pandas.png',
    NUMPY: 'NumPy',
    NUMPY_LOGO: 'assets/images/numpy.png',
    MATPLOTLIB: 'Matplotlib',
    MATPLOTLIB_LOGO: 'assets/images/matplotlib.png',
    OTHER_ML: 'scikit-learn, NLTK, SpaCy, WordCloud, BeautifulSoup, Natural Language Processing (NLP), Seaborn, Machine Learning',
    
    ML_LOGO: 'assets/images/ml.jpeg',
    MISCELLANEOUS: 'Miscellaneous',

    RABBITMQ: 'RabbitMQ',
    RABBITMQ_LOGO: 'assets/images/rabbitmq.png',
    DOCKER: 'Docker',
    DOCKER_LOGO: 'assets/images/docker.png',
    GIT: 'git',
    GIT_LOGO: 'assets/images/git.png',
    FORTRAN: 'Fortran',
    FORTRAN_LOGO: 'assets/images/fortran.png',
    EXCEL: 'MS Excel',
    EXCEL_LOGO: 'assets/images/excel.png',
    DS_ALGO: 'Data structures & Algorithms',
    DS_ALGO_LOGO: 'assets/images/ds_algo.png',
    OS: 'Operating system',
    LINUX: 'Linux',
    LINUX_LOGO: 'assets/images/linux.jpeg',
    WINDOWS: 'Windows',
    WINDOW_LOGO: 'assets/images/window.png',
    DEV_OPS: 'DevOps',
    PUTTY: 'PuTTY',
    PUTTY_LOGO: 'assets/images/putty.png',
    WINSCP: 'WinSCP',
    WINSCP_LOGO: 'assets/images/winscp.jpg',
    JENKINS: 'Jenkins',
    JENKINS_LOGO: 'assets/images/jenkins.png',


}

export const ACHIEVEMENT = {
    JEE_2017: 'JEE',
    JEE: 'Joint Entrance Examination 2017',
    JEE_ACTIVITY: 'Qualified JEE(Main) & JEE(Advanced) among 1.18 million candidates',//'Qualified JEE(Advanced) among 0.15+ million candidates appearing for the test.',
    IITM_LOGO: 'assets/images/iitm.png',
    CGI: 'CGI',
    BRONZE_AWARD: 'Bronze award',
    BRONZE_AWARD_ACTIVITY: 'Received bronze award from president (FY23) and SVP (FY24) & applauds from managers for the excellent work delivered'
}

export const EXTRACURRICULARS ={
    HEADING:'CGI/IITG',
    ACTIVITIES: 'CoS, CSR'
    // CGI_ACTIVITY_TRAINING: 'Qualified Unified Talent Assessment Platform - UTAP\'2022 assessment program and Completed many technical and non-technical courses/training at CGI-skillsoft.',
    // CGI_ACTIVITY_APPLAUDS: 'Appreciation/Applaud, CoS, CCD',
    // CGI_APPLAUD: 'Applaud - Celebrating CGI’s values 2022: Got appreciation letter from scrum master, manager, and Greater Toronto Area lead for the work delivered at CGI.',
    // COMMUNITY_SERVICE: 'Participated in Football & Yoga student’s activity, and been a part of Community Services - CoS during 2017-19',
    // IITG_CCD_VOLUNTEER: 'Participated as a volunteer during the placement season 2019-20 at Centre for Career Development - CCD, IITG'

}
