
export const PROFILE = {
    DEEPAK_MANDAL: "Deepak K. Mandal",
    CGI_IITG: "Software Engineer, CGI || B.Tech, IIT Guwahati",
    PRFILE_PIC: 'assets/images/dkm-profile.jpeg',
    DESCRIPTION: "Deepak has more than 1 year of experience in Software Engineering. He has significant experties in Java technologies, Data structures and algorithms, Spring & Angular framework, SQL & NoSQL databases as well as in developing, debugging, documenting and testing."
}

export const EDUCATION = {
    IIT: 'IIT / B.Tech.',
    IITG: 'Indian Institute of Technology, Guwahati ',
    BTECH: 'Bachelor of Technology',
    SESSION: '2017-2021',
    IITG_LOGO: 'assets/images/IITG.png',
    SENIOR_SECONDARY: 'Senior Secondary'
}

export const EXPERIENCE = {
    CGI: 'CGI',
    CGI_INFO_SYS: 'CGI Information Systems and Management Consultants Pvt. Ltd.',
    SOFTWARE_CONSULTANT: 'Software Engineer / CONSULTANT / Full Stack Developer',
    JAVA_FULL_STACK: 'Foundation skills & Java full-stack immersive training including Product Engineering',
    UI_WORK: 'Worked on Digital Wealth Platform (CGI Wealth360) product features in Angular - Development of new UI screen, Includes building reusable component, services with HTML/SCSS/TS/JS that works in multiple areas of application, service integration with backend API and Testing',
    DAILY_TASK: 'Development, debugging & Testing using Spring (Java), Angular framework, Oracle database on day-to-day basic in the Portfolio and Trading (Capital Markets) Domains for top largest Canadian bank(s)',
    TECHNOLOGIES: 'Technologies used: Java, Spring, Angular, TypeScript/JavaScript, Angular materials, AgGrid, SQL/MySQL/Oracle, NoSQL/MongoDB, Git',
    ASDC: 'Asia Pacific Solutions Delivery Center, Bangalore - India',
    CGI_SESSION: 'Sept 2021-present',
    CGI_LOGO: 'assets/images/cgi.png',
    ACCENTURE: 'Accenture',
    ACCENTURE_SOL: 'Accenture Solutions Pvt. Ltd.',
    LEARNING: 'Pre-Onboard Learning',
    JAVA_ORACLE: 'Java Technologies + Oracle Database',
    ACCENTURE_SESSION: 'Aug - Sept 2021',
    ACCENTURE_LOGO: 'assets/images/ac.png',

}

export const PROJECTS = {
    REVIEWBOOK: 'ReviewBook - Java',
    REVIEWBOOK_PLATFORM: 'ReviewBook Platform',
    CGI_PRODUCT_ENGG: 'CGI - Product Engineering',
    REVIEWBOOK_PROBLEM_STATEMENT: 'Worked on Core Problem - “How to motivate maximum number of consumers to provide genuine reviews and ratings that can influence buying decisions of other consumers”.',
    REVIEWBOOK_ACTITITY: 'Developed Microservices for Registration, Login, Product Management, Review Management, Recommendation Service, Eureka Server, API Gateway; Angular-Spring framework integration.',
    REVIEWBOOK_TECHNOLOGIES: 'Technologies used: Backend - Spring Boot, Mongo DB, MySQL, RabbitMQ; Frontend - Angular, DevOps - Docker, AWS.',
    REVIEWBOOK_SESSION: 'Dec 2021- Jan 2022',
    REVIEWBOOK_LOCATION: 'https://reviewbook.stackroute.io/',
    CONFERENCE_WEB: 'Conference Website - PHP',
    IITG_WEB: 'Conference Website',
    DOC_IITG: 'Department of Chemistry, IITG',
    CONFERENCE_TEAM: 'Developed PHP based full-stack conference web app with my team members.',
    CONFERENCE_DEV: 'Developed the admin portal for the response to edit/delete.',
    CONFERENCE_TECH: 'Technologies used: Backend - PHP, MySQL; Frontend - HTML, CSS & Bootstrap',
    CONFERENCE_SESSION: 'April 2020-June 2020',
    CONFERENCE_LOCATION: 'IIT Guwahati',
    NLP: 'Web and PDF file Data Extraction - NLP',
    NLP_TITLE: 'Web and PDF file Data Extraction',
    NLP_DUEDASH: 'DueDash',
    NLP_ACTIVITY_TEXT: 'Summarization of Text:- Generated the summary from the Source text either web link or PDF file. Further Drawn their Word Cloud',
    NLP_ACTIVITY_IMAGE: 'Text and Image Extraction from any Web Link or URL:- Extraced Images and text data from the web Links and PDF files.',
    NLP_TECH: ' Technologies used: Python3, BeautifulSoup/bs4, PyPDF2, SpaCy, NLTK, WordCloud, NumPy, Shutil, OS, parse, requests',
    NLP_LOGO: 'https://duedash.net/wp-content/uploads/2021/10/DueDash-Large2x.png',
    NLP_SESSION: 'Selected for Product Development & Testing, Internship (work remotely) at Germany based Startup',
    NLP_LOCATION: 'https://github.com/deepak-mandal/DueDash-Germany',
    CRICKET_GAME: 'Cricket Game - Python',
    INTERNSHALA_LOGO: 'assets/images/in.png',
    CRICKET_GAME_PY: 'Fantasy Cricket Game',
    INTERNSHALA: 'Internshala Trainings',
    CRICKET_GAME_ACTIVITY: 'Developed a Python-based desktop application using PyQt framework with SQLite Database.',
    CRICKET_GAME_RESULT: 'assets/images/Project-Fantasy_Cricket_Game_Evaluation.png',
    CRICKET_GAME_SESSION: 'July 2020',
    CRICKET_GAME_LOCATION: 'https://github.com/deepak-mandal/Game',
    ML: 'Price Prediction - Machine learning',
    ML_PREDICTION: 'House Price Prediction',
    ML_TECH: 'Self-paced project using Machine learning technique',
    ML_ACTIVITY: 'Built a Linear Regression Model to Predict the Sale Price of the House based on its characteristics.',
    ML_SESSION: 'April 2021-May 2021',
    ML_LOCATION: 'https://github.com/deepak-mandal/SalePricePrediction',
    AUTOMATION: 'Email Automation',
    AUTOMATION_PY: 'Email Automation with Python',
    SELF_PACED_PROJECT: 'Self-paced project',
    AUTOMATION_ACTIVITY: 'Automating emails by the help of Python, smtplib, Linux & Window OS, HTML, CSS, with attachments using Encrypted connections.',
    AUTOMATION_TECH: 'Extracted emails automatically from the Linkedin Post using selenium, chrome automated test software, re, pandas',
    AUTOMATION_FEATURE: 'Features:- Multiple emails can in one go or on single click, The delivered email is of personalised type i.e. "to" for each single email_Id but not "bcc" or "cc" e-mail type',
    AUTOMATION_SESSION: '2020',
    AUTOMATION_LOCATION: 'https://github.com/deepak-mandal/Email-Automation-with-Python',
    ANALYSIS: 'Text Analysis and Mining',
    ANALYSIS_MINING: 'Wikipedia Text Analytics and Mining',
    ANALYSIS_ACTIVITY: ' Analysed the unstructured data (article) using text mining and created the Word Cloud out of that; to understand what these article trying to say, rather than reading the entire article.',
    ANALYSIS_TECH: 'Technologies used: Python3, WordCloud',
    ANALYSIS_WORD_CLOUD: 'assets/images/tech.png',
    ANALYSIS_SESSION: 'Dec 2020',
    ANALYSIS_LOCATION: 'https://github.com/deepak-mandal/Word-Cloud-from-Text-Mining'
}

export const SKILLS = {
    PROGRAMMING_LANGUAGE: 'Programming languages',
    JAVA: 'Java',
    JAVA_LOGO: 'assets/images/java.png',
    PYTHON: 'Python',
    PY: 'assets/images/py.png',
    JAVASCRIPT: 'JavaScript',
    JS: 'assets/images/js.png',
    TYPESCRIPT: 'TypeScript',
    TS: 'assets/images/ts.png',
    PHP: 'php',
    PHP_LOGO: 'assets/images/php.png',
    WEB_TECHNOLOGIES: 'Web technologies',
    SPRING: 'Spring',
    SPRING_LOGO: 'assets/images/spring.png',
    ANGULAR: 'Angular',
    ANGULAR_LOGO: 'assets/images/angular.png',
    HTML: 'HTML',
    HTML_LOGO: 'assets/images/html.png',
    CSS: 'CSS',
    CSS_LOGO: 'assets/images/css.png',
    BOOTSTRAP: 'BootStrap',
    BOOTSTRAP_LOGO: 'assets/images/bootstrap.jpeg',
    DB: 'Database management',

    ORACLE: 'Oracle',
    ORACLE_LOGO: 'assets/images/oracle.png',
    MONGODB: 'MongoDB',
    MONGODB_LOGO: 'assets/images/mongodb.png',
    MYSQL:'MySQL',
    MYSQL_LOGO: 'assets/images/mysql.png',
    SQLITE: 'SQLite',
    SQLITE_LOGO: 'assets/images/sqlite.png',
    ANALYTICAL_TOOLS: 'Analytical tools',
    PANDAS: 'Pandas',
    PANDAS_LOGO: 'assets/images/pandas.png',
    NUMPY: 'NumPy',
    NUMPY_LOGO: 'assets/images/numpy.png',
    MATPLOTLIB: 'Matplotlib',
    MATPLOTLIB_LOGO: 'assets/images/matplotlib.png',
    OTHER_ML: 'scikit-learn, NLTK, SpaCy, WordCloud, BeautifulSoup, Natural Language Processing (NLP), Seaborn, Machine Learning',
    
    ML_LOGO: 'assets/images/ml.jpeg',
    MISCELLANEOUS: 'Miscellaneous',

    RABBITMQ: 'RabbitMQ',
    RABBITMQ_LOGO: 'assets/images/rabbitmq.png',
    DOCKER: 'Docker',
    DOCKER_LOGO: 'assets/images/docker.png',
    GIT: 'git',
    GIT_LOGO: 'assets/images/git.png',
    FORTRAN: 'Fortran',
    FORTRAN_LOGO: 'assets/images/fortran.png',
    EXCEL: 'MS Excel',
    EXCEL_LOGO: 'assets/images/excel.png',
    DS_ALGO: 'Data structures & Algorithms',
    DS_ALGO_LOGO: 'assets/images/ds_algo.png',
    OS: 'Operating system',
    LINUX: 'Linux',
    LINUX_LOGO: 'assets/images/linux.jpeg',
    WINDOWS: 'Windows',
    WINDOW_LOGO: 'assets/images/window.png',
}

export const ACHIEVEMENT = {
    JEE_2017: 'JEE 2017',
    JEE: 'Joint Entrance Examination 2017',
    JEE_ACTIVITY: 'Qualified JEE(Advanced) among 0.15+ million candidates appearing for the test.',
    IITM_LOGO: 'assets/images/iitm.png',
}

export const EXTRACURRICULARS ={
    HEADING:'CGI/IITG',
    CGI_ACTIVITY_TRAINING: 'Qualified UTAP\'2022 assessment program and Completed 40+ training hour includes technical and non-technical courses at CGI-skillsoft.',
    CGI_ACTIVITY_APPLAUDS: 'Appreciation/Applaud, CoS, CCD',
    CGI_APPLAUD: 'Applaud - Celebrating CGI’s values 2022: Got appreciation letter from Manager.',
    COMMUNITY_SERVICE: 'Participated in Football & Yoga student’s activity, and been a part of Community Services - CoS during 2017-19',
    IITG_CCD_VOLUNTEER: 'Participated as a volunteer during the placement season 2019-20 at Centre for Career Development - CCD, IITG'

}
